services:
  postgres:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: 128mb
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "log_min_duration_statement=1000"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "redis-server"
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "allkeys-lru"
      - "--save"
      - "900 1"
      - "--save"
      - "300 10"
      - "--appendonly"
      - "no"


# open http://localhost:5540 and connect with host redis, port 6379.
# Fix (RedisInsight UI → Add database)
# Use:

# Host: redis
# Port: 6379
# Username / Password: leave blank
# TLS: off
# Then it should connect immediately.

# If you ever run RedisInsight outside compose
# Only then you’d use 127.0.0.1:6379 (from your host). 
# ++ But since you added it to docker-compose.dev.yaml, the correct host is redis.
# RedisInsight → host: redis, port: 6379
# Your app on host → REDIS_URL: redis://localhost:6379
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

volumes:
  pg_data:
  redis_data:
  redisinsight_data: